### ISSUE TITLE
Support of Zabbix v4.4

### ISSUE THREAD

**Issue by mackermann2** [BGmot/zabbix_adgroups#1]
Hello, 
Thanks a lot for your share. That works like a charm on Zabbix v4.2 :) 

But I would like now report alI the modifications on the last version of Zabbix v4.4.0
The authentication works fine but I have the following error when I go to "Administration > General > Auto registration". 
The Apache log file shows this error : 

`[Wed Nov 27 11:34:31.032657 2019] [:error] [pid 3968] [client 127.0.0.1:40652] PHP Fatal error:  Call to undefined method API::Autoregistration() in /var/www/html/zabbix/app/controllers/CControllerAutoregEdit.php on line 51, referer: https://zabbix.ids.saint-gobain.com/zabbix/adm.gui.php?ddreset=1`

Indeed this 
This screen/feature seems to be added in the new version (missing in Zabbix v4.2).
Do you have an idea what I should modify in this code (CControllerAutoregEdit.php) to avoid a HTTP 500 response code ? 

Thanks in advance.

**Comment by BGmot** [comment]
Hi, this repo is obsolete see README. Do keep up with new versions of Zabbix I decided to go alongside main Zabbix repo. Please try tag 4.4.1-bg from https://github.com/BGmot/zabbix and if you still see the problem please create an issue in that repo.

**Comment by mackermann2** [comment]
Thanks for your reply. The problem is resolved by installing from the new repo.
